<?php $_order = $this->getOrder() ?>
<?php $attributes = Mage::helper('edudi_sales')->getSelectedAttributes(); ?>
<div class="grid np">
    <div class="hor-scroll">
        <table cellspacing="0" class="data order-tables">
            <col />
            <!-- product name -->
            <col width="1" />
            <!-- item status -->
            <col width="1" />
            <!-- qty -->
            <?php if (!Mage::helper('edudi_sales')->isPricesHidden()) : ?>
            <col width="1" />
            <!-- original price -->
            <col width="1" />
            <!-- price -->
            <col width="1" />
            <!-- subtotal -->
            <col width="1" />
            <!-- tax amount -->
            <col width="1" />
            <!-- tax percent -->
            <col width="1" />
            <!-- discount amount -->
            <col width="1" />
            <!-- Row Total -->
            <?php endif; ?>

            <?php if (!empty($attributes)) : ?>
            <?php foreach ($attributes as $_attrib) : ?>
            <col width="1" />
            <?php endforeach;?>
            <?php endif; ?>

            <?php if (Mage::helper('edudi_sales')->canShowStock()) : ?>
            <col width="1" />
            <col width="1" />
            <?php endif; ?>

            <?php if (Mage::getStoreConfig('edudi_sales/general/enable')) : ?>
            <col width="1" />
            <?php endif; ?>
            <thead>
                <tr class="headings">
                    <th><?php echo $this->helper('sales')->__('Product') ?></th>

                    <th><span class="nobr"><?php echo
                    $this->helper('sales')->__('Item Status')
                    ?>
                    </span></th>
					<th class="a-center"><?php echo $this->helper('sales')->__('Qty') ?></th>
                    <?php if (!Mage::helper('edudi_sales')->isPricesHidden()) : //hide prices ?>

                    <th><span class="nobr"><?php echo
                    $this->helper('sales')->__('Original Price')
                    ?>
                    </span></th>
                    <th><?php echo $this->helper('sales')->__('Price') ?></th>
                    <th><?php echo $this->helper('sales')->__('Subtotal') ?></th>

                    <th><span class="nobr"><?php echo
                    $this->helper('sales')->__('Tax Amount')
                    ?>
                    </span></th>
                    <th><span class="nobr"><?php echo $this->helper('sales')->__('Tax
Percent') ?> </span></th>

                    <th><span class="nobr"><?php echo
                    $this->helper('sales')->__('Discount Amount')
                    ?>
                    </span></th>
                    <th class="last"><span class="nobr"><?php echo
                    $this->helper('sales')->__('Row Total')
                    ?>
                    </span></th>
                    <?php endif; ?>

                    <?php if (!empty($attributes)) : ?>
                    <?php foreach ($attributes as $_attrib) : ?>

                    <th><span class="nobr"><?php echo
                    $this->helper('sales')->__(!empty($_attrib['frontend_label']) ?
                    $_attrib['frontend_label'] : ucfirst($_attrib['attribute_code']))
                    ?>
                    </span></th>
                    <?php endforeach;?>
                    <?php endif; ?>
                    <?php if (Mage::helper('edudi_sales')->canShowStock()) : ?>

                    <th><span class="nobr"><?php echo
                    $this->helper('sales')->__('Stock Availability')
                    ?>
                    </span></th>
                    <th><span class="nobr"><?php echo $this->helper('sales')->__('Stock
Qty') ?> </span></th>
                    <?php endif; ?>
                    <?php if (Mage::getStoreConfig('edudi_sales/general/enable')) : ?>

                    <th><span class="nobr"><?php echo
                    $this->helper('sales')->__('Actions')
                    ?></span></th>
                    <?php endif; ?>
                </tr>
            </thead>
            <?php $_items = $this->getItemsCollection() ?>
            <?php $i=0;foreach ($_items as $_item):?>
            <?php if ($_item->getParentItem()) continue; else $i++;?>
            <tbody class="<?php echo $i%2?'even':'odd' ?>">
                <?php echo $this->getItemHtml($_item) ?>
                <?php echo $this->getItemExtraInfoHtml($_item) ?>
            </tbody>
            <?php endforeach; ?>
        </table>
    </div>
</div>
<br />
